# Generated by Django 5.2.7 on 2025-11-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='El porcentaje de impuesto', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='RegionTaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(help_text='Codigo de region', max_length=10, unique=True)),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.taxrate')),
            ],
        ),
    ]
