# Generated by Django 5.2.7 on 2025-11-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('ordered', 'Ordenado')], default='active', max_length=10),
        ),
    ]
