# Generated by Django 5.2.7 on 2025-11-12 09:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_shoppingcart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_at_addition',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio del producto al momento de agregar al carrito', max_digits=10),
        ),
    ]
