# Generated by Django 5.2.7 on 2025-11-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_invoice_pdf_remove_order_tax_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/%d'),
        ),
    ]
